#!/usr/bin/env bash
# uninstall.sh - reverses what install.sh set up.
#
# Default (safe):   removes ./android, the generated ./compile script and the
#                   ~/.bashrc block. Your Rust code, Cargo.toml and keystore are untouched.
#
# Optional flags:
#   --tools      also remove cargo-ndk and the Rust Android targets
#   --sdk        also remove the NDK / platform / build-tools that install.sh installed
#   --keystore   also DELETE the release keystore + signing entries in ~/.gradle/gradle.properties
#   --all        all of the above
#   -y, --yes    do not ask for confirmation

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

ANDROID_HOME="${ANDROID_HOME:-$HOME/Android/Sdk}"
NDK_VERSION="${NDK_VERSION:-28.2.13676358}"
PLATFORM="${PLATFORM:-35}"
BUILD_TOOLS="${BUILD_TOOLS:-35.0.0}"
ABIS="${ABIS:-arm64-v8a}"
GRADLE_PROPS="$HOME/.gradle/gradle.properties"
MARK_BEGIN="# >>> rust-android >>>"
MARK_END="# <<< rust-android <<<"

DO_TOOLS=0; DO_SDK=0; DO_KEYSTORE=0; ASSUME_YES=0
for arg in "$@"; do
  case "$arg" in
    --tools)    DO_TOOLS=1 ;;
    --sdk)      DO_SDK=1 ;;
    --keystore) DO_KEYSTORE=1 ;;
    --all)      DO_TOOLS=1; DO_SDK=1; DO_KEYSTORE=1 ;;
    -y|--yes)   ASSUME_YES=1 ;;
    -h|--help)  sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown option: $arg (see --help)" >&2; exit 1 ;;
  esac
done

info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarn:\033[0m %s\n' "$*" >&2; }

confirm() {
  [ "$ASSUME_YES" -eq 1 ] && return 0
  read -r -p "$1 [y/N] " ans
  [[ "$ans" =~ ^[Yy]$ ]]
}

abi_to_triple() {
  case "$1" in
    arm64-v8a)   echo aarch64-linux-android ;;
    armeabi-v7a) echo armv7-linux-androideabi ;;
    x86_64)      echo x86_64-linux-android ;;
    x86)         echo i686-linux-android ;;
  esac
}

echo "This will remove:"
echo "  - ./android (generated Gradle project + build outputs)"
echo "  - ./compile (only if generated by install.sh)"
echo "  - the rust-android block in ~/.bashrc"
[ "$DO_TOOLS" -eq 1 ]    && echo "  - cargo-ndk and Rust Android targets ($ABIS)"
[ "$DO_SDK" -eq 1 ]      && echo "  - SDK: NDK $NDK_VERSION, platform $PLATFORM, build-tools $BUILD_TOOLS"
[ "$DO_KEYSTORE" -eq 1 ] && echo "  - release keystore and signing credentials  (IRREVERSIBLE)"
confirm "Continue?" || { echo "Aborted."; exit 0; }

# --- project files ---------------------------------------------------------
if [ -d android ]; then
  info "Removing ./android"
  rm -rf android
fi

if [ -f compile ] && grep -q 'generated by install.sh' compile; then
  info "Removing ./compile"
  rm -f compile
fi

# --- ~/.bashrc block -------------------------------------------------------
if grep -qF "$MARK_BEGIN" "$HOME/.bashrc" 2>/dev/null; then
  info "Removing environment block from ~/.bashrc"
  sed -i "/$MARK_BEGIN/,/$MARK_END/d" "$HOME/.bashrc"
fi

# --- rust tooling ----------------------------------------------------------
if [ "$DO_TOOLS" -eq 1 ]; then
  if command -v cargo-ndk >/dev/null 2>&1; then
    info "Uninstalling cargo-ndk"
    cargo uninstall cargo-ndk || true
  fi
  if command -v rustup >/dev/null 2>&1; then
    for abi in $ABIS; do
      info "Removing Rust target $(abi_to_triple "$abi")"
      rustup target remove "$(abi_to_triple "$abi")" || true
    done
  fi
fi

# --- android sdk pieces ----------------------------------------------------
if [ "$DO_SDK" -eq 1 ]; then
  SDKMANAGER="$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager"
  if [ -x "$SDKMANAGER" ]; then
    info "Removing SDK packages"
    "$SDKMANAGER" --sdk_root="$ANDROID_HOME" --uninstall \
      "ndk;$NDK_VERSION" "build-tools;$BUILD_TOOLS" "platforms;android-$PLATFORM" || true
  else
    warn "sdkmanager not found at $SDKMANAGER, skipping SDK removal"
  fi
  echo "Note: $ANDROID_HOME itself, cmdline-tools and platform-tools were left in place."
  echo "      Delete the folder manually if nothing else uses it: rm -rf $ANDROID_HOME"
fi

# --- keystore --------------------------------------------------------------
if [ "$DO_KEYSTORE" -eq 1 ] && [ -f "$GRADLE_PROPS" ]; then
  KS="$(sed -n 's/^RELEASE_STORE_FILE=//p' "$GRADLE_PROPS" | head -1)"
  if [ -n "$KS" ] && [ -f "$KS" ]; then
    warn "Deleting $KS - apps signed with it can no longer be updated!"
    confirm "Really delete the keystore?" && rm -f "$KS"
  fi
  info "Removing signing entries from $GRADLE_PROPS"
  sed -i '/^RELEASE_STORE_FILE=/d;/^RELEASE_STORE_PASSWORD=/d;/^RELEASE_KEY_ALIAS=/d;/^RELEASE_KEY_PASSWORD=/d' "$GRADLE_PROPS"
fi

info "Done. Open a new terminal so the environment changes take effect."
echo "Left untouched: src/, Cargo.toml (incl. the [lib] cdylib section), .gitignore."